export class ExamCompletionDTO {
    constructor(
      public examId: number,
      public studentEmail: string,
      public turkishCorrectCount: number,
      public mathCorrectCount: number,
      public scienceCorrectCount: number,
      public historyCorrectCount: number,
      public religionCorrectCount: number,
      public foreignLanguageCorrectCount: number,
      public turkishWrongCount: number,
      public mathWrongCount: number,
      public scienceWrongCount: number,
      public historyWrongCount: number,
      public religionWrongCount: number,
      public foreignLanguageWrongCount: number,
      public turkishWrongSubjects: string,
      public mathWrongSubjects: string,
      public scienceWrongSubjects: string,
      public historyWrongSubjects: string,
      public religionWrongSubjects: string,
      public foreignLanguageWrongSubjects: string,
      public turkishEmptySubjects: string,
      public mathEmptySubjects: string,
      public scienceEmptySubjects: string,
      public historyEmptySubjects: string,
      public religionEmptySubjects: string,
      public foreignLanguageEmptySubjects: string,
    ) {}
}